# Generated by Django 2.1.2 on 2018-10-26 09:59

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DMA', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='area_6_DMAs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_1', models.CharField(max_length=254)),
                ('field_2', models.CharField(max_length=254)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
        migrations.DeleteModel(
            name='DMA',
        ),
    ]
