# Generated by Django 2.1.2 on 2018-10-26 12:02

import DMA.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DMA', '0003_area_6_dmas_leakage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area_6_dmas',
            name='leakage',
            field=models.IntegerField(default=0, verbose_name=DMA.models.random_int),
        ),
    ]
