# Generated by Django 2.1.2 on 2018-10-26 12:05

import DMA.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DMA', '0004_auto_20181026_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area_6_dmas',
            name='leakage',
            field=models.IntegerField(default=DMA.models.random_int),
        ),
    ]
