# Generated by Django 2.1.2 on 2018-10-30 07:19

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DMA', '0005_auto_20181026_1305'),
    ]

    operations = [
        migrations.CreateModel(
            name='area_6_bursts',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=254)),
                ('point', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
    ]
