# Generated by Django 2.1.2 on 2018-10-30 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DMA', '0006_area_6_bursts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='area_6_bursts',
            old_name='point',
            new_name='geom',
        ),
        migrations.AlterField(
            model_name='area_6_bursts',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='area_6_bursts',
            name='type',
            field=models.CharField(max_length=20),
        ),
    ]
